---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  attributes:
    apt:
      compiletime: true

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-7.0
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
  driver_config:
    box: opscode-centos-7.0
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-7.0_provisionerless.box
- name: centos-6.5
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box
- name: centos-5.9
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: varnish3
  excludes:
    - centos-7.0
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '3.0'
- name: varnish4
  excludes:
    - centos-5.9
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '4.0'
